### ISSUE TITLE
OpenGL implementation

### ISSUE THREAD

**Issue by AntonioNoack** [GPUOpen-Effects/FidelityFX-FSR2#10]
Hello,

A lot of applications still use OpenGL, so it would be nice, if there was an OpenGL implementation as well. Just like for FSR 1.0.
I haven't looked into the source code yet, but it should be possible, I think. At least with Compute Shaders, in case shared memory is being used.

**Comment by rys** [comment]
Unfortunately we've got no plans for an OpenGL implementation ourselves, but if someone else implements one we'd review any PR and consider landing it. The GLSL shaders for the Vulkan implementation are there as the starting point.

**Comment by ImUrX** [comment]
could the issue be opened so people interested on making a PR easily find it?

**Comment by Calinou** [comment]
> Sorry for bumping but what's wrong with GL?

There's nothing wrong with OpenGL, but that API is becoming less common in modern games/applications in favor of Vulkan. This is especially the case with recent OpenGL versions (4.3+) which are rarely used in games/applications, as most OpenGL backends favor compatibility with old hardware and therefore stick to OpenGL 3.3 (sometimes less).

**Comment by mirh** [comment]
https://jntesteves.github.io/shadesofnoice/graphics/shaders/upscaling/2021/09/11/amd-fsr-demystified.html

**Comment by mirh** [comment]
And there it its
https://github.com/JuanDiegoMontoya/FidelityFX-FSR2-OpenGL
https://old.reddit.com/r/opengl/comments/148dcwh/opengl_port_of_fsr_2/

**Comment by RusJJ** [comment]
> And there it its

Damn, now i need GLES 3.x for a full setup :|
(There is FSR 1.x version but that's not cool - a shader nuh-uh)

**Comment by mirh** [comment]
FSR1 *is* basically just a shader, duh-uh?
And who knows, perhaps the requirements can be lowered with a bit of elbow grease (even though usually it's the newer extensions and hardware features that make for the biggest optimizations in performance)

**Comment by g-exp** [comment]
> And there it its https://github.com/JuanDiegoMontoya/FidelityFX-FSR2-OpenGL https://old.reddit.com/r/opengl/comments/148dcwh/opengl_port_of_fsr_2/

Great effort for GL, and suppose it's kind of official work? Since I noticed that author's also from AMD.

**Comment by JuanDiegoMontoya** [comment]
> > And there it its https://github.com/JuanDiegoMontoya/FidelityFX-FSR2-OpenGL https://old.reddit.com/r/opengl/comments/148dcwh/opengl_port_of_fsr_2/
> 
> Great effort for GL, and suppose it's kind of official work? Since I noticed that author's also from AMD.

To be clear, that is **not** an official OpenGL backend. I made it in my spare time to support my personal projects. Of course, anyone is welcome to use it and contribute to its development, but don't expect it to be optimal (in any sense of the word) or supported by anyone other than myself.
