### ISSUE TITLE
[Feature Request] Do not forget about FSR 2 Native (TAA-only mode)

### ISSUE THREAD

**Issue by SaltyBet** [GPUOpen-Effects/FidelityFX-FSR2#109]
As mentioned [here](https://youtu.be/97JIldpUGE4?t=2337):

![FSR 2 Native ](https://user-images.githubusercontent.com/66281060/234744573-0e722d8a-1618-431a-8a85-b45a5d126a22.png)

... which would be AMD's counter to [DLAA](https://en.wikipedia.org/wiki/Deep_learning_anti-aliasing).

If this was delayed as an FSR 3 feature, it's OK, but please do not forget about it, Team AMD.

**Comment by SaltyBet** [comment]
By the way, [DLSS2FSR ](https://github.com/PotatoOfDoom/CyberFSR2) kinda already allows this unofficially by using custom scale factor via [INI file](https://github.com/PotatoOfDoom/CyberFSR2/blob/main/nvngx.ini) _(see QualityOverrides section)_.

**Comment by JohnnyJosda** [comment]
Fsr3 disappeared like this, and only TAA did not appear either

**Comment by JohnnyJosda** [comment]
> 顺便说一下，[DLSS2FSR ](https://github.com/PotatoOfDoom/CyberFSR2) 已经通过 [INI 文件](https://github.com/PotatoOfDoom/CyberFSR2/blob/main/nvngx.ini)使用自定义比例因子非正式地允许这样做_（请参阅质量覆盖部分）。_
What does this mean, changing this ini file so that they only have anti aliasing?
Does it mean to set the scaling ratio in the ini file to 1?

**Comment by SaltyBet** [comment]
And so, according to:

https://gpuopen.com/presentations/2023/AMD_FidelityFX_Super_Resolution_3-Overview_and_Integration.pdf

... page 47:

#### NEW FSR 3 QUALITY MODE: NATIVE AA
- FSR 3 introduces a new Quality mode: Native AA
- In this mode FSR 3 Upscaling is a pure AA option (no actual upscaling tal<es place)

... it is done.

I guess I can close this feature request.

Thanks, Team AMD.
