### ISSUE TITLE
Unreal Engine 5.2 updated plugin?

### ISSUE THREAD

**Issue by oscarbg** [GPUOpen-Effects/FidelityFX-FSR2#112]
Hi,
didn't know where to ask, so asking here..
thanks..

**Comment by rdeforest** [comment]
To add some detail to this, when rebuilding UE5 with FSR2, there are hundreds of errors. Some of them are `variable "int32" is not a type name`, which is obviously not what's actually going on. A bunch of others are `'IsFeatureLevelSupported': identifier not found` except there are other identifiers not being found as well.

In the case of IsFeatureLevelSupported, this is exported from /Engine/Source/Runtime/RHI/Public/RHIDefinitions.h, which is included in FSR2TemporalUpscaling.h. I haven't looked at the diffs of UE 5.1.1 vs 5.2, but I suspect some of the headers have been reorganized such that some stopped including headers they used to include and FSR2 was depending on those now-broken relationships.

Before I go digging around further I'd like to hear if any of this elicits an "a-ha!" response from anyone.

**Comment by g-exp** [comment]
UE5.2 plugin already published on amd website

**Comment by oscarbg** [comment]
Thanks.. closing..
