### ISSUE TITLE
DirectX 11 support

### ISSUE THREAD

**Issue by artsemionov** [GPUOpen-Effects/FidelityFX-FSR2#16]
Is there a reason why you are not publishing a version for DirectX 11? I saw that you offer to contact an AMD representative to discuss this topic. However, if I'm just an indie developer, do I have a chance to get it?

**Comment by DevonAA** [comment]
No Direct X 11 prevents me from using this too.
I've read the same about it being offered by contacting AMD.
Is it experimental and not ready yet?

**Comment by Milor123** [comment]
oh yes, we need the code for DirectX 11. The vast majority of games are in Dx11 T_T
Thank you very much and please share the Dx11 Support when you can !!!

**Comment by imniko** [comment]
Don't know what is the technical limitation on releasing DX11 source, its really disappointing.

**Comment by Milor123** [comment]
@rys What do you think bro?

**Comment by rys** [comment]
Sorry folks, we don't have any plans to release the DX11 version source unfortunately. It's a question of support (as always), and we only have the resources to maintain the DX12 and Vulkan versions in the public release.

**Comment by imniko** [comment]
How about releasing the source and mark it archived or deprecated or abandoned or unsupported? Isn't that what open source is suppose to be? Also the main reason people wanting dx11 source is to mod FSR2 in some older titles that are never going to get an update anyway.

**Comment by Milor123** [comment]
> How about releasing the source and mark it archived or deprecated or abandoned or unsupported? Isn't that what open source is suppose to be? Also the main reason people wanting dx11 source is to mod FSR2 in some older titles that are never going to get an update anyway.

if this is true! Also, as I mentioned before, The God of War has an implementation of FSR 2 with DX11, although it may be incomplete and they will not maintain it any longer, surely we can do a lot with that source code. We would be very grateful if you can release that experimental DX11 code you used in the God of War game. Please reconsider helping us by sharing that code. @rys

**Comment by PureDark** [comment]
> How about releasing the source and mark it archived or deprecated or abandoned or unsupported? Isn't that what open source is suppose to be? Also the main reason people wanting dx11 source is to mod FSR2 in some older titles that are never going to get an update anyway.

Seconded.
You don't have to maintain DX11 version, just release and mark abandoned, we really need source code for DX11 version.

**Comment by Rinshun** [comment]
The excuse that they don't have the resources to mantain it isn't convincing, because they have the option of publishing it and let the community do their thing.

**Comment by imniko** [comment]
We are seeing how much support and maintenance is going on for the DX12/Vulkan version since the comment was made. Its been nothing but a joke, their lame excuse is just pathetic.

**Comment by doctashay** [comment]
Would really like to see this released as well. As others have said, mark the release as abandoned - if you don't want to support it, then don't.

**Comment by KingOwnageXV** [comment]
> > How about releasing the source and mark it archived or deprecated or abandoned or unsupported? Isn't that what open source is suppose to be? Also the main reason people wanting dx11 source is to mod FSR2 in some older titles that are never going to get an update anyway.
> 
> Seconded. You don't have to maintain DX11 version, just release and mark abandoned, we really need source code for DX11 version.
> 
> EDIT: I somehow got FSR 2.1 working on DX11 by using a DX11/DX12 hybrid rendering system, look like everything is working fine.
> 
> EDIT2: It does work pretty well, although 10 FPS lower than native DX11 DLSS, but still a significant FPS gain comparing to native 4K.

Can you go into detail on how you used a hybrid rendering mode on FSR 2 to get it working on DX11 titles? If you can't go into detail here I have Twitter and Discord but my teams upcoming game uses DX11 and I'm having issues contacting AMD. If you could help out in any way I'd be very grateful. Thanks in advanced!

**Comment by PureDark** [comment]
> > > > > How about releasing the source and mark it archived or deprecated or abandoned or unsupported? Isn't that what open source is suppose to be? Also the main reason people wanting dx11 source is to mod FSR2 in some older titles that are never going to get an update anyway.
> > > > 
> > > > 
> > > > Seconded. You don't have to maintain DX11 version, just release and mark abandoned, we really need source code for DX11 version.
> > > > EDIT: I somehow got FSR 2.1 working on DX11 by using a DX11/DX12 hybrid rendering system, look like everything is working fine.
> > > > EDIT2: It does work pretty well, although 10 FPS lower than native DX11 DLSS, but still a significant FPS gain comparing to native 4K.
> > > 
> > > 
> > > Can you go into detail on how you used a hybrid rendering mode on FSR 2 to get it working on DX11 titles? If you can't go into detail here I have Twitter and Discord but my teams upcoming game uses DX11 and I'm having issues contacting AMD. If you could help out in any way I'd be very grateful. Thanks in advanced!
> > 
> > 
> > Yeah like I can't explain it in details, but try creating a separate DX12 device and a shared fence, then create shared textures for the color, depth and motion vectors. Sharing textures between dx11 and dx12 is very easy, you can find a lot of examples on the internet. Make sure to use the shared fence for synchronization, that means wait for FSR2's gpu job is completed before doing any furthur draw calls on the dx11 side.
> 
> Can I ask why you would why you would add a dx12 device to a directx11 only game? That's not making sense to me but I'd love to know - thanks!

For doing FSR2, that's what you asked about.
It's like this, game rendering in dx11 -> fsr2 processing in dx12 -> share back to dx11 for presenting in dx11 swapchian.

**Comment by mbucchia** [comment]
Don't know if it has been posted before, but there is a well-hidden patch from AMD themselves adding DX11 support, specifically for Unity, but the patch can be applied to the SDK and used for non-Unity engines too:

https://github.com/GPUOpen-Effects/FidelityFX-FSR2-Unity-URP/blob/main/src/patch/0001-fsr-2.2-dx11-backend.patch

**Comment by Snipy44** [comment]
> > How about releasing the source and mark it archived or deprecated or abandoned or unsupported? Isn't that what open source is suppose to be? Also the main reason people wanting dx11 source is to mod FSR2 in some older titles that are never going to get an update anyway.
> 
> Seconded. You don't have to maintain DX11 version, just release and mark abandoned, we really need source code for DX11 version.
> 
> EDIT: I somehow got FSR 2.1 working on DX11 by using a DX11/DX12 hybrid rendering system, look like everything is working fine.
> 
> EDIT2: It does work pretty well, although 10 FPS lower than native DX11 DLSS, but still a significant FPS gain comparing to native 4K.

Hello PureDark do you think is possible to enable FSR / DLSS / FG for GTA V / FiveM RP Mod?
