### ISSUE TITLE
Always true condition in `VK/Renderer.cpp`

### ISSUE THREAD

**Issue by qarmin** [GPUOpen-Effects/FidelityFX-FSR2#2]
https://github.com/GPUOpen-Effects/FidelityFX-FSR2/blob/c8fc17d281665927e414b6b8117873cccbac0990/src/VK/Renderer.cpp#L686

**Comment by rys** [comment]
While that short circuit will always prep the input resources for the reactive mask generation, [a later check](https://github.com/GPUOpen-Effects/FidelityFX-FSR2/blob/c8fc17d281665927e414b6b8117873cccbac0990/src/VK/Renderer.cpp#L853) will ensure correct behaviour.

We will rework that in a future release to fix it, well spotted.
