### ISSUE TITLE
UE4 Plugin: Sharpness has no effect

### ISSUE THREAD

**Issue by KristofMorva** [GPUOpen-Effects/FidelityFX-FSR2#20]
Hey FSR team,

I can't seem to get Sharpness working in PIE. FSR2 itself works, and I have done the following:
- tried setting `r.FidelityFX.FSR2.Sharpness` to 1 in the console
- tried setting it to 1 in project settings
- if I query it via the console, I correctly get back 1
- just in case I've set `r.Tonemapper.Sharpen` to 0 too (setting it to non-zero has a clear sharpening effect)
- tried restarting the editor in case it'd be initialized only once - no change
- tried standalone, doesn't work there either
- switching between 1 and 0 in the console, there's clearly no effect - no pixels change whatsoever

Is there any further step needed to get sharpening working?

**Comment by RadioArtz** [comment]
Didn't seem to work for me aswell at first but after enabling "Temporal Upsampling" in the Project Settings it worked (although now the entire image is pretty noisy in some areas with loads of fireflies going on. probably down to configuration though)

**Comment by KristofMorva** [comment]
Ohh jeez, thanks @RadioArtz, I am stupid; I made a switch so that the player can choose between TAAU and FSR, and when FSR is selected, TAAU was switched off - I didn't realize that it's actually a prerequisite of FSR.

Now there's some shaking left around glasses, but will test through the different parameters, hopefully one of those will be able to fix it up

https://user-images.githubusercontent.com/5695015/176763841-a4c801a2-ce40-4523-84db-c4fabadab1ed.mp4

Thanks again! 😄
