### ISSUE TITLE
When debugging, 0xc0000005 error is reported

### ISSUE THREAD

**Issue by JackJiang888** [GPUOpen-Effects/FidelityFX-FSR2#30]
When debugging,  error occurs when allocating staticGeometryMem, just as belows
![C939B278-41F9-405d-BF79-2E4A095E88BB](https://user-images.githubusercontent.com/100114482/177680679-81957a3d-edd5-4cdc-9902-7c80f95035d9.png)

**Comment by JackJiang888** [comment]
In FSR2, the length read from scene.bin is only 134

![image](https://user-images.githubusercontent.com/100114482/177708171-60eb4b30-dc33-4247-a20c-3840314452c8.png)

the real is 404669684

![image](https://user-images.githubusercontent.com/100114482/177708483-00dfb85b-0647-4532-9dcd-038c9c938af4.png)

**Comment by JackJiang888** [comment]
In FSR1, it is all right
![image](https://user-images.githubusercontent.com/100114482/177709094-cf840a4e-65b0-4e64-8cc4-33c045bf751b.png)

**Comment by JackJiang888** [comment]
Sloved, through git lfs big data

**Comment by Andy-YX** [comment]
> Sloved, through git lfs big data

Hello, I met the same issue. Could you please teach me how to solve it using 'git lfs big data'? Thanks!

**Comment by JackJiang888** [comment]
using git-lfs clone


------------------------------------------------------------------
发件人：Andy-YX ***@***.***>
发送时间：2022年8月11日(星期四) 08:19
收件人：GPUOpen-Effects/FidelityFX-FSR2 ***@***.***>
抄　送：Zhikang Jiang ***@***.***>; State change ***@***.***>
主　题：Re: [GPUOpen-Effects/FidelityFX-FSR2] When debugging, 0xc0000005 error is reported (Issue #30)

Sloved, through git lfs big data
Hello, I met the same issue. Could you please teach me how to solve it using 'git lfs big data'? Thanks!

**Comment by Riga27527** [comment]
> > Sloved, through git lfs big data
> 
> Hello, I met the same issue. Could you please teach me how to solve it using 'git lfs big data'? Thanks!

Hi, I have the same issuse. Have you solved the problem? Does using 'git lfs big data' mean that something is missing during recursive cloning? Thanks!
