### ISSUE TITLE
GLSL support not mentioned in README

### ISSUE THREAD

**Issue by Calinou** [GPUOpen-Effects/FidelityFX-FSR2#4]
From a quick search, FSR 2.0 does have GLSL code options available (like FSR 1.0): https://github.com/GPUOpen-Effects/FidelityFX-FSR2/search?q=glsl

However, the README doesn't mention it. Having a GLSL option makes integration in many Vulkan applications easier, so it should be mentioned.

**Comment by rys** [comment]
We'll document that in the next update as also mentioned in #5.
