### ISSUE TITLE
Is it possible to provide a command-line Windows tool for FSR2?

### ISSUE THREAD

**Issue by Andy-YX** [GPUOpen-Effects/FidelityFX-FSR2#44]
Hello, 

Is it possible to provide a command-line Windows tool for FSR2 like the one for FSR1 so that FSR2 could be tested and evaluated on any images?

Thanks!

**Comment by Calinou** [comment]
Since FSR 2.0 relies on motion vectors (unlike FSR 1.0), this is not technically feasible.

**Comment by Andy-YX** [comment]
> Since FSR 2.0 requires motion vectors (unlike FSR 1.0), an offline upscaling tool is not technically feasible.
> 
> If you need high-quality offline upscaling, consider something like [waifu2x](https://github.com/nihui/waifu2x-ncnn-vulkan) or [ESRGAN](https://github.com/joeyballentine/esrgan).

Thanks for the info.
