### ISSUE TITLE
linux building support

### ISSUE THREAD

**Issue by K1ngst0m** [GPUOpen-Effects/FidelityFX-FSR2#6]
Will the recently public push have Linux building support, also `GenerateSolutions` scripts support?

**Comment by rys** [comment]
We have no plans for specific Linux platform support for the sample, but we designed FSR2 so that integrations into games that run on other platforms are definitely possible.

**Comment by ericwomer** [comment]
> We have no plans for specific Linux platform support for the sample, but we designed FSR2 so that integrations into games that run on other platforms are definitely possible.

So basically you're saying M$ gave you guys cash to keep it off Linux for developers? Cause there is no other reason not to support developing on Linux.

**Comment by rys** [comment]
> So basically you're saying M$ gave you guys cash to keep it off Linux for developers? Cause there is no other reason not to support developing on Linux.

Not at all (and it's sad to hear someone think that). We have a finite number of engineers working on our projects and it's just a resourcing call the business makes. I would personally love to support Linux, and I have lobbied for it internally, but we can't justify it. I will continue to fight for it.

**Comment by ericwomer** [comment]
> > So basically you're saying M$ gave you guys cash to keep it off Linux for developers? Cause there is no other reason not to support developing on Linux.
> 
> Not at all (and it's sad to hear someone think that). We have a finite number of engineers working on our projects and it's just a resourcing call the business makes. I would personally love to support Linux, and I have lobbied for it internally, but we can't justify it. I will continue to fight for it.

Yeah, I'm sorry about what I said and accused you guys of. I'm just upset and tired of feeling like Linux developers (and users) are being targeted by corporations and made the mistake of taking it out on you guys personally. Thank you for your work and I hope you don't assume all Linux developers and users are like me.

**Comment by ericwomer** [comment]
> Will the recently public push have Linux building support, also `GenerateSolutions` scripts support?

You can check out https://github.com/TheJackiMonster/FidelityFX-FSR2, I don't know how to get it to work and I don't know how to get in touch with the repo owner to ask, but there is a pr explaining some things, https://github.com/GPUOpen-Effects/FidelityFX-FSR2/pull/60

**Comment by TheJackiMonster** [comment]
@ericwomer If you just want to build the libraries on Linux:

- Clone the repository: `git clone https://github.com/TheJackiMonster/FidelityFX-FSR2.git`
- Ignore the code from the cauldron sample and go to the directory of FSR2: `cd src/ffx-fsr2-api/`
- Create a directory to build into and go into that new directory: `mkdir build && cd build/`
- Setup cmake to build only with the Vulkan bindings (ignoring DirectX12): `cmake -DFFX_FSR2_API_DX12=OFF -DFFX_FSR2_API_VK=ON ..`
- Build the libraries: `make -j $(nproc)`

The only requirement at the moment is that you have `wine` installed because I haven't implemented a shell/bash replacement for the `FidelityFX_SC.exe` in the repository yet. That would be easier if the source code was available. ^^'

**Comment by alvinsat** [comment]
Hello again, I am sorry taking a while. I got this error
```
CMake Warning (dev) in CMakeLists.txt:
  No project() command is present.  The top-level CMakeLists.txt file must
  contain a literal, direct call to the project() command.  Add a line of
  code such as

    project(ProjectName)

  near the top of the file, but after cmake_minimum_required().

  CMake is pretending there is a "project(Project)" command on the first
  line.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) in CMakeLists.txt:
  cmake_minimum_required() should be called prior to this top-level project()
  call.  Please see the cmake-commands(7) manual for usage documentation of
  both commands.
This warning is for project developers.  Use -Wno-dev to suppress it.

-- The C compiler identification is AppleClang 14.0.0.14000029
-- The CXX compiler identification is AppleClang 14.0.0.14000029
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at CMakeLists.txt:45 (message):
  Unsupported target platform - only supporting x64 and Win32 currently
```

**Comment by alvinsat** [comment]
I tried to bypassing platform check and force it to run as x64 insted. But then I realized mac m1 did not support vulkan

```
Will build FSR2 library: Vulkan backend
CMake Error at /opt/homebrew/Cellar/cmake/3.26.3/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find Vulkan (missing: Vulkan_LIBRARY Vulkan_INCLUDE_DIR) (found
  version "")
Call Stack (most recent call first):
  /opt/homebrew/Cellar/cmake/3.26.3/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
  /opt/homebrew/Cellar/cmake/3.26.3/share/cmake/Modules/FindVulkan.cmake:597 (find_package_handle_standard_args)
  vk/CMakeLists.txt:55 (find_package)

```

**Comment by alvinsat** [comment]
I hear something called MoltenVK for vulkan on mac m1 with metal api. I will maybe try it and see the result later
